### ISSUE TITLE
Replace header image

### ISSUE THREAD

**Issue by RahulBansal0502** [QAZIMAAZARSHAD/Voters-Registration-Portal#181]
In my view, if we make the header in this way like first the heading will be written in English then below that in Hindi. 

I want to work on this issue. Assign it to me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Okk go ahead.

**Comment by QAZIMAAZARSHAD** [comment]
@RahulBansal0502 you can replace the 'register to vote' image in the header with flag.png on every page.

**Comment by RahulBansal0502** [comment]
I will replace this but this is not a Level0 issue. There are so many loop holes in the code.

**Comment by QAZIMAAZARSHAD** [comment]
> I will replace this but this is not a Level0 issue. There are so many loopholes in the code.

@RahulBansal0502 you have to only replace vote.png with flag.png on three pages.
I don't think this is anyway a little more than zero level.


Also, the levels label in the issue is just temporary, most of the times I have increased or decreased the level according to the efforts of the contributor, lines of code written and the PR made.

**Comment by RahulBansal0502** [comment]
Oh ok, I understand now I have to only replace my header image now only.
