### ISSUE TITLE
Display result on clicking submit button

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#5]
A pop-up window with a "form successfully submitted" message should appear or it should navigate to another page displaying form submitted message.

**Comment by shivshankar9** [comment]
Assign to me I will do.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by hv65616** [comment]
**Hello @QAZIMAAZARSHAD, This is Himanshu Verma, and I am a B.tech from CSE student.**
**If you consider me, I would love to contribute to this issue and make it successfully resolved.**
**If you like you can check my LinkedIn as well as Github**

- LinkedIn:- [https://www.linkedin.com/in/himanshu-verma-94a1a41b8/](url)

**Comment by QAZIMAAZARSHAD** [comment]
@hv65616 I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Ananyaiitbhilai** [comment]
> A pop-up window with a "form successfully submitted" message should appear or it should navigate to another page displaying form submitted message.

Since there is no info about backend in this repo so, I don't exactly how you will be calling that page "Successfully Submitted", but what I can figure out is that from the current status is that, host that page individually and then that would be rendered after submitting the form and its link would be embedded in this tag <ahref="" input type="submit" style="margin-bottom:10px !important; margin-left:8px; font-weight: bold;" class="btn btn-success" value="Submit"></a>

**Comment by kumarishalini6** [comment]
@QAZIMAAZARSHAD can I work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD can I work on this issue

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.
Keep in mind, since many contributors are willing to work on this issue, only the best solution/design will be accepted.

**Comment by QAZIMAAZARSHAD** [comment]
@kumarishalini6 and @shivshankar9 if you had some better idea, you are welcome to open a new issue to improve.
